@startuml general
hide footbox

actor frontEnd

participant postService
participant notificationService

== create post ==
group Add post non-media data
  frontEnd -> postService: Request to create post
  postService -> frontEnd: created post id
end
group Add options groups non-media data
  frontEnd -> postService: Request to create option groups
  postService -> frontEnd: option groups and options ids
end
group Add media if found
  frontEnd -> postService: Request to add media if found
  postService -> frontEnd: acknowledgement
end
group Flag post as finished
  frontEnd -> postService: Request to flag post as finished
  postService -> frontEnd: success
end

== get post ==
frontEnd -> postService : Request to get post
postService -> frontEnd : post data

== add vote ==
frontEnd -> postService : Add vote
postService -> frontEnd : options vote count
postService -> notificationService : create notification

== request notifications ==
frontEnd -> notificationService : request notifications
notificationService -> frontEnd : notifications

== update notifications ==
frontEnd -> notificationService : update notifications
notificationService -> frontEnd : updated

@enduml