@startuml
hide footbox

participant client
participant mediaService 
participant uploadService
participant provider1
participant provider2
participant providerN

client -> mediaService : Request upload
mediaService -> uploadService : Binary File
uploadService -> provider1: Upload Request1
uploadService [#Blue]-> provider2: Upload Request2
uploadService [#Green]-> providerN: Upload Request3

provider2 [#Blue]-> uploadService : Upload Response2
providerN [#Green]-> uploadService : Upload Response3
provider1 -> uploadService : Upload Response1 (Fastest respone)
uploadService -> mediaService : URL (Fastest respone)
mediaService -> client : Masked URL (Fastest respone)

@enduml