---
openapi: 3.0.0
info:
  description: "Post Service API Specs"
  version: 1.0.0
  title: Pickly Post Service
tags:
  - name: posts
    description: Posts endpoints
  - name: votes
    description: voting endpoint
paths:
  "/posts":
    post:
      tags:
        - posts
      summary: Create a new post
      operationId: create
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              "$ref": "#/components/schemas/postCreationBody"
      responses:
        "201":
          description: Post Created Successfully
          "$ref": "#/components/responses/CreatedPost"
        "400":
          description: Bad request
          "$ref": "#/components/responses/BadRequestError"
        "401":
          "$ref": "#/components/responses/UnauthorizedError"
components:
  schemas:
    postCreationBody:
      type: object
      properties:
        caption:
          type: string
          example: "test caption"
        isHidden:
          type: boolean
          example: false
        type:
          type: string
          enum: [text, image, miniSurvey]
          example: "text"
        options:
          oneOf:
            - $ref: "#/components/schemas/textOptions"
            - $ref: "#/components/schemas/imageOptions"
            - $ref: "#/components/schemas/miniSurveyOptions"
      required: ["isHidden", "type"]
    textOptions:
      type: array
      items:
        type: string
      example: ["option 1", "option 1"]
    imageOptions:
      type: array
      items:
        type: string
        format: binary
    miniSurveyOptions:
      "$ref": "#/components/schemas/miniSurvey"
    miniSurvey:
      type: object
      properties:
        image:
          type: string
          format: binary
        groups:
          type: array
          items:
            type: object
            properties:
              groupTitle:
                type: string
              textOptions:
                type: array
                items:
                  type: string
    GenericError:
      type: object
      properties:
        message:
          type: array
          items:
            type: string
          example: ["error1", "error2"]
        statusCode:
          type: number
          default: 123
  securitySchemes:
    firebaseAuth:
      type: http
      scheme: bearer
  responses:
    CreatedPost:
      description: Post created successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                example: "some-id"
              imageUrls:
                type: array
                items:
                  type: string
                example: ["url1", "url2"]
    BadRequestError:
      description: Bad Request Error occured
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/GenericError"
    UnauthorizedError:
      description: Unauthorized. Access token is missing or invalid
    
servers:
  - description: Try it Now
    url: https://pickly-posts-be-dev.m3ntorship.net/
